#!/bin/bash

if [ -z "$IP" ]; then
	echo "Error: please set the IP envrionment variable for the test device."
	exit 1
fi

if [ -z "$SSHPASS" ]; then
	echo "Error: please set the SSHPASS envrionment variable for the test device."
	exit 1
fi

echo "Building for ARM64 device ..."
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build ./cmd/purenet

echo "Testing on device with IP=$IP ..."
sshpass -e scp -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" purenet root@$IP:/root/
sshpass -e ssh -q -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@$IP /bin/bash -c "/root/purenet"

